### ISSUE TITLE
Update for A12 Devices Please 

### ISSUE THREAD

**Issue by ahanank** [gilshahar7/ExactTime#2]
Could you please compile it for the latest A12 devices? Getting a preference bundle error :/

**Comment by gilshahar7** [comment]
Yes i will fix this today. Sorry for the wait

**Comment by gilshahar7** [comment]
Updated, the deb file can be found in the source code under "packages".

Will be on Packix soon

**Comment by ahanank** [comment]
You are too awesome! Thank you! Really appreciate it
