### ISSUE TITLE
iOS 14.3 compatibility

### ISSUE THREAD

**Issue by robertybob** [gilshahar7/ExactTime#5]
Hello! Having just upgraded to 14.3 I would love to have this tweak working for me, is there any chance of you confirming ios 14 compatibility, or updating the tweak so it'll work on ios 14?

**Comment by gilshahar7** [comment]
Hey, the tweak should work on iOS 14.3, have you downloaded it to check?

Let me know if you are facing issues :)

**Comment by robertybob** [comment]
I was worried in case it messed anything up, but I’ve just installed it and can confirm it’s working fine on my iPhone XS running iOS 14.3 unc0ver  :)
